### ISSUE TITLE
example on how to send out images

### ISSUE THREAD

**Issue by joaquingrech** [Sarel-Esterhuizen/GroqSharp#2]
I want to send out an image and ask questions about it. For instance, upload a picture of the fridge and ask "what do you see?".
Any way to do that with this library?

**Comment by Sarel-Esterhuizen** [comment]
Thanks for your question.

As it stands, Groq hosts open-source text completion models, and the API is designed to be compatible with OpenAI clients for text completions. This is precisely why I developed this client. Since Groq's current focus is solely on text completions, I opted to streamline this client to support that use case specifically, without incorporating multi-modal capabilities that aren't supported by Groq's existing features (I hate using packages that are bloated and like to keep things simple).

As such, at the moment, the client supports chat completions exclusively. However, I'm closely monitoring Groq's developments, and should they introduce support for multi-modal use cases in the future, I will definitely consider expanding this client's functionalities to include such features.
